export const enums = {
  roles: { 0: "", 1: "일반사용자", 2: "관리자", 3: "시스템관리자" },
  departments: ["HR팀", "법무팀", "영업팀"],
  company_affiliation: ["아모레퍼시픽그룹", "아모레퍼시픽", "설화수"],
  positions: ["사원", "대리", "팀장", "과장", "차장", "부장", "임원"],
  employment_status: ["재직", "휴직", "정직"],
  all_employment_status: ["재직", "휴직", "정직", "퇴직"],
};

export const ourBrands = [
  { name: "설화수", img_path: "/img/logo/설화수.png" },
  { name: "라네즈", img_path: "/img/logo/라네즈.png" },
  { name: "이니스프리", img_path: "/img/logo/이니스프리.png" },
  { name: "에이피뷰티", img_path: "/img/logo/에이피뷰티.png" },
  { name: "헤라", img_path: "/img/logo/헤라.png" },
  { name: "프리메라", img_path: "/img/logo/프리메라.png" },
  { name: "아이오페", img_path: "/img/logo/아이오페.png" },
  { name: "마몽드", img_path: "/img/logo/마몽드.png" },
  { name: "한율", img_path: "/img/logo/한율.png" },
  { name: "에스트라", img_path: "/img/logo/에스트라.png" },
  { name: "에스쁘아", img_path: "/img/logo/에스쁘아.png" },
  { name: "에뛰드", img_path: "/img/logo/에뛰드.png" },
  { name: "려", img_path: "/img/logo/려.png" },
  { name: "미쟝센", img_path: "/img/logo/미쟝센.png" },
  { name: "라보에이치", img_path: "/img/logo/라보에이치.png" },
  { name: "아윤채", img_path: "/img/logo/아윤채.jpg" },
  { name: "아모스프로페셔널", img_path: "/img/logo/아모스프로페셔널.png" },
  { name: "롱테이크", img_path: "/img/logo/롱테이크.png" },
  { name: "일리윤", img_path: "/img/logo/일리윤.png" },
  { name: "해피바스", img_path: "/img/logo/해피바스.png" },
  { name: "스킨유", img_path: "/img/logo/스킨유.png" },
  { name: "메디안", img_path: "/img/logo/메디안.png" },
  { name: "젠티스트", img_path: "/img/logo/젠티스트.png" },
  { name: "구딸", img_path: "/img/logo/구딸.png" },
  { name: "바이탈뷰티", img_path: "/img/logo/바이탈뷰티.png" },
  { name: "메이크온", img_path: "/img/logo/메이크온.png" },
  { name: "오딧세이", img_path: "/img/logo/오딧세이.png" },
  { name: "비레디", img_path: "/img/logo/비레디.png" },
  { name: "홀리추얼", img_path: "/img/logo/홀리추얼.jpg" },
  { name: "오설록", img_path: "/img/logo/오설록.png" },
];

export const boardCategory = {
  NEWS: ["전체", "기업", "브랜드", "연구개발", "사회공헌", "지속가능경영"],
  BRAND: [
    "전체",
    "화장품",
    "향수",
    "메디컬뷰티",
    "뷰티",
    "디바이스",
    "이너뷰티",
    "헤어케어",
    "바디케어",
    "덴탈케어",
    "티컬처",
  ],
  DOCUMENT: ["전체", "실적발표", "사업보고서", "영업보고서", "기타 IR자료"],
};
