export const enums = {
  roles: { 0: "", 1: "일반사용자", 2: "관리자", 3: "시스템관리자" },
  brand_ctgry: {
    BEAUTY_CARE: "화장품",
    PERFUME: "향수",
    MEDICAL_BEAUTY: "메디컬뷰티",
    BEAUTY_DEVICE: "디바이스",
    INNER_BEAUTY: "이너뷰티",
    HAIR: "헤어",
    BODY: "바디",
    ORAL_CARE: "덴탈",
    TEA_CULTURE: "티컬처",
  },
  post_type: {
    NEWS: "뉴스",
    REPORT: "보고서",
    JOURNAL: "저널",
    DOCS: "문서",
  },
};

export const select_items = {
  departments: [
    "경영전략",
    "마케팅",
    "물류",
    "법무",
    "생산",
    "영업",
    "재무",
    "커뮤니케이션",
    "HR",
    "IT",
    "R&I",
  ],
  company_affiliation: [
    "아모레퍼시픽그룹",
    "아모레퍼시픽",
    "설화수",
    "라네즈",
    "이니스프리",
    "에이피뷰티",
    "헤라",
    "프리메라",
    "아이오페",
    "마몽드",
    "한율",
    "에스트라",
    "에스쁘아",
    "에뛰드",
    "려",
    "미쟝센",
    "라보에이치",
    "아윤채",
    "아모스프로페셔널",
    "롱테이크",
    "일리윤",
    "해피바스",
    "스킨유",
    "메디안",
    "젠티스트",
    "구딸",
    "바이탈뷰티",
    "오설록",
    "메이크온",
    "오딧세이",
    "비레디",
    "홀리추얼",
  ],
  positions: ["사원", "대리", "팀장", "과장", "차장", "부장", "임원"],
  employment_status: ["재직", "휴직", "정직"],
  all_employment_status: ["재직", "휴직", "정직", "퇴직"],
};

export const boardCategory = {
  NEWS: [
    { name: "전체", value: "" },
    { name: "기업", value: "기업" },
    { name: "브랜드", value: "브랜드" },
    { name: "연구개발", value: "연구개발" },
    { name: "사회공헌", value: "사회공헌" },
    { name: "지속가능경영", value: "지속가능경영" },
  ],
  BRAND: [
    { name: "전체", value: "" },
    { name: "화장품", value: "BEAUTY_CARE" },
    { name: "향수", value: "PERFUME" },
    { name: "메디컬뷰티", value: "MEDICAL_BEAUTY" },
    { name: "디바이스", value: "BEAUTY_DEVICE" },
    { name: "이너뷰티", value: "INNER_BEAUTY" },
    { name: "헤어", value: "HAIR" },
    { name: "바디", value: "BODY" },
    { name: "덴탈", value: "ORAL_CARE" },
    { name: "티컬처", value: "TEA_CULTURE" },
  ],
  REPORT: [
    { name: "전체", value: "" },
    { name: "재무제표", value: "재무제표" },
    { name: "실적발표", value: "경영실적" },
    { name: "사업보고서", value: "사업보고서" },
    { name: "영업보고서", value: "영업보고서" },
    { name: "기타IR", value: "기타IR" },
  ],
};

export const externalCategory = {
  NEWS: [{ name: "코스인코리아닷컴", value: "코스인코리아닷컴" }],
  JOURNAL: [
    { name: "코스메틱리포트", value: "코스메틱리포트" },
    { name: "ALLURE", value: "ALLURE" },
  ],
  COSMETIC: [
    { name: "전체", value: "" },
    { name: "스킨", value: "스킨" },
    { name: "메이크업", value: "메이크업" },
    { name: "클렌징", value: "클렌징" },
    { name: "선케어", value: "선케어" },
    { name: "바디", value: "바디" },
    { name: "헤어", value: "헤어" },
  ],
};
