name: Deploy Amoresearch Backend to EC2

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"  # 백엔드 디렉토리 변경시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/projects/amore_search  # 프로젝트 루트로 이동
            git pull origin main

            cd backend
            # 기존 컨테이너 중지 및 삭제
            sudo docker stop amoresearch-backend || true
            sudo docker rm amoresearch-backend || true

            # 새 컨테이너 빌드 및 실행
            sudo docker build -t amoresearch-backend -f Dockerfile .
            sudo docker run -d --name amoresearch-backend -p 8000:8000 --restart=always amoresearch-backend
